%%{init: {"theme": "base", "themeVariables": {"background": "#FFFFFF", "mainBkg": "#FFFFFF", "primaryColor": "#E8F8F4", "primaryBorderColor": "#43C6B6", "primaryTextColor": "#20343C", "secondaryColor": "#9EE7D2", "tertiaryColor": "#8FD3F4", "lineColor": "#2F9FD0", "defaultLinkColor": "#2F9FD0", "clusterBkg": "#F5FBFB", "clusterBorder": "#43C6B6", "nodeBorder": "#2F9FD0", "edgeLabelBackground": "#FFFFFF", "fontFamily": "Garamond"}}}%%
flowchart TD
    A(Extract MQTT / API / SQL) --> B("B̶r̶o̶n̶z̶e̶ cuivre !<br/>Stockage brut JSON")
    B --> C(Validation technique)
    C --> D(Chargement PostgreSQL)
    D --> E(Modèles dbt)
    E --> F(Détection excursions)
    F --> G(Table alertes qualité)
    G --> H(Dashboard + notification)
