apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: PostgreSQL - événements
    uid: postgres-events
    type: postgres
    access: proxy
    url: postgres:5432
    user: pharma_data
    jsonData:
      database: pharma_analytics
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: pharma_local_only
    editable: false
